### ISSUE TITLE
support multi segment path regex

### ISSUE THREAD

**Issue by muntact** [faceyspacey/redux-first-router#139]
I'm trying to compile a 'deep link' to a path that contains multiple 'subroutes' or repeated path segments, and i noticed that the path-to-regexp library supports this, however the actionToPath `_payloadToParams` method throws away array args.

https://github.com/pillarjs/path-to-regexp#compile-reverse-path-to-regexp

```js
var toPathRepeated = pathToRegexp.compile('/:segment+')

toPathRepeated({ segment: 'foo' }) //=> "/foo"
toPathRepeated({ segment: ['a', 'b', 'c'] }) //=> "/a/b/c"
```

Was this just something that was missed, or is this use case intentionally unsupported?

**Comment by faceyspacey** [comment]
the `@rudy` branch on NPM supports this:

https://github.com/faceyspacey/redux-first-router/blob/rudy/src/pure-utils/actionToPath.js#L45

let me know if something is missing.

Also, before upgrading, make sure to check all the notes at the top of the readme. there's info about all the latest changes.

**Comment by faceyspacey** [comment]
i think the difference is you still must pass your payload as a string, but the string can contain slashes between segments. 

If we were to accept arrays in the payload, we'd also have to do the opposite in pathToAction, somewhere around here:

https://github.com/faceyspacey/redux-first-router/blob/rudy/src/pure-utils/pathToAction.js#L57

I'm not opposed to it, but it's ultimately a minor optimization since you can do the same in this rarer case within `to/fromPath`.

**Comment by muntact** [comment]
Thanks, the implementation on the rudy branch did work for my use case.

Out of curiosity when will the `rudy` branch become master / get a 1.x release (is there some feature milestones you're looking to hit first)?

**Comment by faceyspacey** [comment]
This month
