### ISSUE TITLE
Why does history have to be stored in state?

### ISSUE THREAD

**Issue by waynebloss** [faceyspacey/redux-first-router#145]
When navigation happens, the router should be able to get everything from the url to deduce the action type and parameters from it, to dispatch the action...

So, why does the navigation history get stored?

**Comment by faceyspacey** [comment]
It's currently only in React Native (or whenever memory history is used):

https://github.com/faceyspacey/redux-first-router/blob/master/src/pure-utils/nestAction.js#L33

That said, it will become an integral part of the next release, as we'll have index and back/next tracking + entries, even in the browser. I've found a way to make it very dependable, even though the browser history API does not give you access to such info. 

There's a lot of things you can do with this information. I'll be discussing it in a future blog post, but if you have checked out *React Navigation* before you will see they have an action creator `setParams` which can set state on a given route in an array. This will facilitate that among other things. Perhaps the simplest example is simply having a guarantee on the direction the user is going (backwards or forwards), which you can use to trigger animation transitions seamlessly. In the past, you had to do this in an application specific way based on the direction the user is *likely* to go when transitioning from one given page to another given page. You can only go so far with that. 

Anyway, we've gotten used to a life where we can't access such info because the browser said so. So we just kinda tell ourselves there's nothing useful we can do with it. Not anymore. And there's lots of high valuable things you can do with knowing exactly where you are moving along a history entries track.

So anyway what you're seeing in the code is just stuff intended for React Native, but now will soon be available to all.

**Comment by waynebloss** [comment]
Thanks for your answer. I am using rfr in a web app right now and the `location` state that `redux-persist` puts in localStorage includes all the history. So, I'm going to have to write a transformer to stop that from happening because I don't want it there. (I was going to write one anyway to stop my temporary states from being saved.)

**Comment by faceyspacey** [comment]
are you using memory history? it shouldn't be there currently if ur using memory history

**Comment by faceyspacey** [comment]
it must be coming from the server and then is rehydrated.

**Comment by waynebloss** [comment]
No, I'm not using SSR. I'm also not specifying memory history or anything like that - just using the default options (and passing querySerializer).

My only call to a RFR function is pretty much here:

```js
connectRoutes(routesMap, {
      // basename: '/',
      querySerializer: queryString,
    });
```

**Comment by waynebloss** [comment]
I did notice that SSR was one of the main focuses here and I considered not using RFR because I thought there might not have been too much testing done *without* SSR. But, I'm here to help with finding those issues.

I'm not building a web app that needs SEO, so SSR is not a big concern of mine.

**Comment by faceyspacey** [comment]
that's something i've thought about lately as well. many people do use it without SSR. my codesandboxes dont have SSR. but other than that I personally always go with SSR.

**Comment by waynebloss** [comment]
Thanks for your consideration! My server platform is not Node.js so adding SSR to my particular app would be a real PITA.

**Comment by alexduhanov** [comment]
@faceyspacey: Sorry to resurrect a dead thread but in the second post above, you said:

> we'll have index and back/next tracking + entries, even in the browser. I've found a way to make it very dependable, even though the browser history API does not give you access to such info.

Is this something that ever got implemented? I've been trying to figure out a way to differentiate between back/next navigation with browser history alone.
