### ISSUE TITLE
Not dispatching thunks when arriving directly on route without SSR

### ISSUE THREAD

**Issue by benoneal** [faceyspacey/redux-first-router#151]
Our application does not use SSR. Route thunks are correctly dispatched when navigating client-side via NavLinks, but are never dispatched when going directly to a url. This includes refreshing a page. 

For example, if you arrive directly at the home route, then navigate to a resource route, it will dispatch the thunk associated with that route, and fetch the data. If you then refresh at the same url, the thunk will not be dispatched and the page will be lacking all data.

**Comment by faceyspacey** [comment]
- what version of RFR are you using? if you're new to it you likely don't want to use the `@rudy` tag/branch.
- what does your `location` state look like?
- can you paste me your store configuration code

Also fyi, if you pass `initialDispatch: false` as an option to `connectRoutes`, you can get access to the `initialDispatch` function and dispatch it yourself. It's returned from `connectRoutes:

```js
const { reducer, initialDispatch, etc } = connectRoutes(history, routesMap, { initialDispatch: false })

// finish configuring store

initialDispatch()
```

You shouldn't have to do that, which is why I'm thinking perhaps this is a bug with the upcoming versions of RFR/Rudy.

**Comment by benoneal** [comment]
I've tried both `@rudy` and `master`. I'm using `master` right now, but the bug exists in both (just tested `@rudy` again to confirm). Here's (the relevant portions of) my code: 

```js
// routes.js
import {getDestinations, getDestination} from './api'
import {setResourceType, setActiveResource} from './actions'

const handleDestinationsRoute = (dispatch, getState) =>
  getDestinations().then(destinations => 
    dispatch(setResourceType('destinations', destinations)))
...
export default { 
  DESTINATIONS: {path: '/destinations', thunk: handleDestinationsRoute},
  EDIT_DESTINATION: {path: '/destinations/:id', thunk: handleEditDestinationRoute},
  ADD_DESTINATION: {path: '/destinations/add', thunk: handleAddDestinationRoute}
}

// store.js
const {
  reducer: location, 
  middleware: routerMiddleware, 
  enhancer
} = connectRoutes(createHistory(), routes) // I remove createHistory() when using @rudy

const middlewares = [
  routerMiddleware, 
  appMiddleware, 
  DEV && logger
].filter(Boolean)

const rootReducer = combineReducers({location, app})
const createStoreWithMiddleware = applyMiddleware(...middlewares)(createStore)

export default createStoreWithMiddleware(rootReducer, {app: getInitialState()}, compose(
  enhancer, 
  DEV && window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()
))
```

Location state when directly loading `/destinations`:
```js
{
  location: {
    pathname: '/destinations',
    type: 'DESTINATIONS',
    payload: {},
    prev: {
      pathname: '',
      type: '',
      payload: {}
    },
    kind: 'load',
    routesMap: {
      DESTINATIONS: {
        path: '/destinations'
      },
      EDIT_DESTINATION: {
        path: '/destinations/:id'
      },
      ADD_DESTINATION: {
        path: '/destinations/add'
      }
    }
  }
}
```

Location state after navigating in the runtime via a link on the page that links to the same path (which triggers the thunk correctly):
```js
{
  location: {
    pathname: '/destinations',
    type: 'DESTINATIONS',
    payload: {},
    prev: {
      pathname: '',
      type: '',
      payload: {}
    },
    kind: 'load',
    routesMap: {
      DESTINATIONS: {
        path: '/destinations'
      },
      EDIT_DESTINATION: {
        path: '/destinations/:id'
      },
      ADD_DESTINATION: {
        path: '/destinations/add'
      }
    }
  }
}
``` 

And this is the only action (after `@@INIT`) that has fired on page load: 
```js
{
  type: 'DESTINATIONS',
  payload: {},
  meta: {
    location: {
      current: {
        pathname: '/destinations',
        type: 'DESTINATIONS',
        payload: {}
      },
      prev: {
        pathname: '',
        type: '',
        payload: {}
      },
      kind: 'load'
    }
  }
}
```

**Comment by faceyspacey** [comment]
yes, that's how it works with SSR. If it has SSR and it's load, the thunk isn't called:

https://github.com/faceyspacey/redux-first-router/blob/master/src/pure-utils/attemptCallRouteThunk.js#L26

I was thinking possibly somehow your system thought it had SSR, but `hasSSR` isn't true (or defined) in your `location` state, so that doesn't seem to be the issue. The latest non-rudy tag on NPM is in fact an `@next` tag which was released before the `@rudy` branch started. It's possible that a bug was introduced there. You may want to do `npm info` and install the precise last version that wasn't `@next`...I'll do it for you--it's `1.9.19`.

One thing weird about this one:
> Location state after navigating in the runtime via a link on the page that links to the same path (which triggers the thunk correctly):

It has `kind === 'load'` which would never be the case on navigation, since you just clicked a link. It should be `push`. There's something weird going on here.

..Another thing: I see you're using `preloadedState` even though you aren't doing SSR. That may be causing it. It shouldn't, but it could.

Otherwise, I won't have much time to help you on the old version, as I'm trying to get out the new version asap. I'd just do the `initialDispatch` thing I mentioned. It's what people who use sagas, for example, use. So they can setup their sagas before the initial dispatch. The other option is to use version `1.9.19`. Now that said, it also may not work, as I haven't heard this problem from anyone else using new or old versions. There could be something weird going on, which your setup has uncovered for the first time. If you feel like getting to the bottom of it, try logging everything in all the `if` statements below:

https://github.com/faceyspacey/redux-first-router/blob/master/src/pure-utils/attemptCallRouteThunk.js#L19

Something is simply blocking it from being called. The code you have in `node_modules/redux-first-router/pure-utils/attemptCallRouteThunk.js` may be a bit different, and perhaps that's the bug.

**Comment by benoneal** [comment]
I think I've found the problem. [You're creating the `initialState`](https://github.com/faceyspacey/redux-first-router/blob/rudy/src/connectRoutes.js#L178) artificially, and not via dispatching an action. Because you're not dispatching an action, the middleware is not called with any action. Because it's not called, the logic surrounding `attemptCallRouteThunk` is never evaluated, and so obviously the route thunk is never going to be executed. 

Basically, `attemptCallRouteThunk` can *never* be called on direct page load, because its only call sites are within the `action` portion of the middleware, which is never called on page load because no actions are dispatched.

I've confirmed the above with the following: 
```js
const log = console.log.bind(console)
const middleware = log('middleware') || (store: Store) => log('store') || (next: Next) => log('next') || (action: Action) => { log('action') ...
```
and observed that only the following was output: 
```
middleware
store
next
```

I've tested the following change and confirmed that it fixes my immediate issue. I'm sure the logic isn't quite robust enough to just drop this code in, but I would appreciate you looking into pushing a fix for this soon. This is a bug in the feature that would affect anyone building a client-side app which relies on thunks to preload data for routes. 

```js
// line 225:
const middleware = (store: Store) => {
  if (routesMap[type] && routesMap[type].thunk) {
    attemptCallRouteThunk(
      store.dispatch,
      () => ({location: INITIAL_LOCATION_STATE}),
      routesMap[type],
      selectLocationState,
      { action: {type, payload}, extra }
    )
  }
  return (next: Next) => (action: Object) => {
    ...etc
```

Basically, the thunk for any route needs to be executed asap on load. The internal flow control of `attemptCallRouteThunk` is sufficient to determine if it shouldn't execute because of SSR or whatever. 

Although the implementation is completely different, you can see an example of how I've addressed this issue [in my redux router](https://github.com/benoneal/naglfar/blob/master/src/index.js#L102). The middleware looks like this: 
```js
  return (store) => {
    history.listen((location) => {
      store.dispatch(navigation.locationChange(location))
    })
```
This takes advantage of the fact that the `history` lib will, on load, call listeners for the initial location event, and so dispatches a location change which brings the store into sync with the url. In this way, directly visiting a url vs internally navigating the app is handled identically. Food for thought.

**Comment by faceyspacey** [comment]
The action is dispatched here:

https://github.com/faceyspacey/redux-first-router/blob/rudy/src/connectRoutes.js#L509

There's only 2 reasons it wouldn't be called:

- you passed `initialDispatch: false`
- or `locationState.hasSSR === true`:
https://github.com/faceyspacey/redux-first-router/blob/rudy/src/connectRoutes.js#L493

Can you evaluate what's happening in your enhancer to prevent this from happening :)

**Comment by faceyspacey** [comment]
perhaps the enhancer is not even set up, or enhancer ordering issues are coming into play. 

Is your listening to your history (i.e. when you press the back/next buttons)?

**Comment by benoneal** [comment]
Ah ok. I didn't see that you were doing that sort of work in the enhancer. TBH it looks like there's a fair amount of duplication of logic/concerns between the enhancer and the middleware. 

It turns out it was an enhancer ordering issue. The bug was caused by this: 
```js
const enhancers = [
  enhancer,
  DEV && window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()
].filter(Boolean)

const rootReducer = combineReducers({location, app, fetch})
const createStoreWithMiddleware = applyMiddleware(...middlewares)(createStore) // these middleware aren't involved until after the store is set up and actions dispatched in the enhancer

export default createStoreWithMiddleware(rootReducer, compose(...enhancers))
```

... and fixed by this: 
```js
const enhancers = [
  enhancer,
  applyMiddleware(...middlewares),
  DEV && window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()
].filter(Boolean)

const rootReducer = combineReducers({location, app, fetch})

export default createStore(rootReducer, compose(...enhancers))
```

Since you're not extending/monkey patching the store instance, I'm not sure what value you're getting from having the enhancer, that couldn't be gained by using the store passed to the first layer of the middleware. If you consolidated this into just middleware, you'd avoid ordering problems altogether. Just an idea in case you see other issues with enhancer ordering. 

I'm closing this issue now because my immediate problem is resolved.

**Comment by benoneal** [comment]
(Oh, and yeah, my router listens to and handles back/next history transitions.)

**Comment by faceyspacey** [comment]
This stuff originally existed in the middleware long ago. The problem is if you call `store.dispatch` that early on, the entire middleware chain isn't created yet:

https://github.com/reactjs/redux/blob/7bac7ecb0d15c164035576177d191d2c461d01e6/src/applyMiddleware.js#L29

> and if you call it once passed `dispatch` (i.e. after it receives its second argument), you miss any middleware that came before.

So by doing it in the enhancer you guarantee everything will run as expected *(in terms of the middleware)*. I'm definitely open to doing it all in the middleware if it can be done. Ultimately, you'll run into the same problem that if anything came before the RFR middleware it won't be called. Enhancers are less of a problem because that's not where people do as much.

There are 2 approaches though:
- `setTimeout(stuffCurrentlyInEnhancer)` when called on setup of the middleware would solve it, since by the time it ran, the middleware would be setup. 

- since we won't be automatically dispatching the first route anymore, that also will solve the problem. We just have to return references to functions like `initialDispatch` which close over `_initialDispatch`, which itself isn't defined until `applyMiddleware` is called.

That said, the next version of RFR has a very different architecture with its own middleware based on koa. And it's created in the enhancer in a specialized way, and hi-jacks actions from the regular middleware, and then runs them through an async *but sequential* promise-based middleware. The current incarnation on my computer in fact only returns an enhancer. So there's no setting up of middleware, reducer, etc. ..got something big coming--i'll look into what else i can stuff into middleware regardless. Thanks for pointing this out.
