### ISSUE TITLE
The History peer dependency should be on history v3

### ISSUE THREAD

**Issue by conartist6** [faceyspacey/redux-first-router#152]
History v2 does not define createBrowserHistory().location, which is used in this library.

**Comment by faceyspacey** [comment]
Good find. Ultimately, the next version of RFR will have its own `history` package called `smart-history`. It's very much a complete rewrite, with some extra special things in store. So that will fix itself naturally. It will also depend on the package, rather than require users to provide it (though that will still be available as an option for custom histories).

So with that said I'm going to close this. The new stuff will be out very shortly.
