### ISSUE TITLE
Title doesn't get sync'ed for actions dispatched in the route thunks

### ISSUE THREAD

**Issue by w9** [faceyspacey/redux-first-router#171]
I ran into a situation where the title value depends on something that's not in the payload of the route action---I have to fetch it in the route thunk. But since the RFR middleware only changes [*immediately* after a route thunk](https://github.com/faceyspacey/redux-first-router/blob/master/src/connectRoutes.js#L345-L353), It won't sync if dispatch another action in the route thunk that changes (via the "title" reducer) the title.

I wonder if this is intentional, and if yes then what's the idiomatic way?

**Comment by faceyspacey** [comment]
You gotta set document.title yourself. It's not based on an independent subscription to the store. It updates in response to route actions. This feature is just setting document.title, so the idiomatic way outside of route changes is to manually set it.

**Comment by w9** [comment]
Thanks @faceyspacey.

For anyone looking at this thread, here is what I ended up doing:

```javascript
// reducers/title.js
export default (state = 'My App', action) => {
  switch (action.type) {
    case ROUTE1:
    case ROUTE2:
    case ROUTE3:
    case ROUTE4: {
      const { prop1, prop2 } = action.payload;
      return `My App - ${prop1} - ${prop2}`;
    }

    case SET_STATE_AFTER_DATA_RETRIEVAL: {
      const { title } = action.payload;
      if (typeof document !== 'undefined') {
        // `setTimeout` is necessary here so that it will happen after
        // https://github.com/faceyspacey/redux-first-router/blob/master/src/connectRoutes.js#L345-L353
        setTimeout(() => {
          document.title = title;
        });
      }
      return title;
    }

    default:
      return state;
  }
};
```

**Comment by faceyspacey** [comment]
Just a little nitpick: basically the philosophy is to keep your reducers pure. I'd just do 

```js
let prevTItle

store.subscribe(() => { 
   const title = store.getState().title
   if(prevTitle !=== title)  {
      document.title = title
      prevTitle = title
   }
}
```

When it comes to testing it will make your reducers easier to test--for example they won't require `window.document` or mocked timers or anything. You can likely get away just fine with what you did, but it's just recommended best practice to not put side-effects in reducers.

**Comment by w9** [comment]
@faceyspacey Yeah that makes a lot of sense, thanks!

**Comment by w9** [comment]
@faceyspacey I realized I would still need to have it wrapped up in a `setTimeout`. I wonder if there's a away for me to disable the auto title setting by RFR?

**Comment by faceyspacey** [comment]
There will be in the next major release. Assigning the title option to an empty function should do the trick as it only changes it the title has changed.

**Comment by Grsmto** [comment]
@faceyspacey I just saw this feature was existing when reading the doc. I'm usually (and I think lot of people do) use React-Helmet for this kind of thing.
Isn't this feature out of scope of RFR? I wouldn't expect the router to do this out of the box.

**Comment by faceyspacey** [comment]
I understand where ur coming as this is not the norm,  it firstly who defines scope?

...Why, so u gotta do tons more work, passing state to components, embedding helmet, and handle it who knows where in your component tree.

Most developers use React Router and Redux when this exists, which is retarded. The whole industry is doing it wrong with all the bullshit they are doing in the view layer which should be moved to a controller layer. There’s no opinion, this is hands down 1000x better and the correct way for Redux. Let the learners and influencers who no longer build and only cater to learners keep you stuck in their “component everything” approach. In that approach u r correct; in an MVC-like system that has controllers, it makes sense here, rather than through components doing the same thing where purity should be had instead. The controller is closer to the title than the view is, and requires no hacks.

Forget helmet, forget what everyone else is doing. The router does it because it commonly changes when the url changes, and it enforces/teaches how to use a reducer to produce your title.

I wasn’t trying to come off abrasive, just know they are doing it wrong and we are doing it right, which is a different paradigm from the mainstream :) jk, kinda
