### ISSUE TITLE
what stops to get closer to 1.0.0?

### ISSUE THREAD

**Issue by Guria** [faceyspacey/redux-first-router#172]
I have tried `redux-first-router` and was very happy to use it. It is much more better then `react-router` if you ask me. In [cerebral](https://cerebraljs.com) we have router solution with pretty same idea (tie to controller instead of view layer) and was happy to find same ideas in redux world.

But `redux-first-router` has now a pretty scary version number `0.0.16-next.` Is there any stoppers to get stable API close to 1.0.0? I'd like to hear it and help with getting closer to this milestone.
I can also share my experience with building and using `@cerebral/router` and underlying `url-mapper` and `urlon` libraries.

**Comment by davidfurlong** [comment]
Perhaps we could build a milestone for Rudy, as I want to swap from react-router more and more, but I'm not sure how big of a change the rudy release will be // how much time it will take to migrate to it.

**Comment by faceyspacey** [comment]
@Guria RFR is very stable. And the rudy + next tags/branches are very stable as well. You have no need to worry about the scary version number. ..Nice to hear your thoughts regarding being tied to the controller rather than the view layer. Obviously we are very much in agreement in the real need to revert to the old ways in React/Reduxlandia. A lot of experimentation has happened to make components the *be-all-end-all*, but it's been counter-productive and completely unnecessary for real apps. React apps have been ad hoc slops of mess as a result of not having a proper framework-like approach. Basically we all stand to benefit from our view layer having proper deep integrations to our model layer (redux) and the controller layer (routing/Rudy). 

@davidfurlong Rudy is gonna be a huge release and I've been working on it full time since my last updates noted at the top of the readme. I decided to take this concept all the way. I'll be sharing a lot about it very soon. It won't be too hard to migrate and we'll have a migration guide, but it will have a lot of breaking changes. It will be worth it though. Lots of new stuff!

**Comment by davidfurlong** [comment]
@faceyspacey I know it may be hard to estimate time until release but can I ask which timeframe you think is most likely:
a) 0 - 4 weeks away
b) 4 - 8 weeks away
c) 8 - 12 weeks away
d) 12 weeks +

**Comment by faceyspacey** [comment]
A

**Comment by waynebloss** [comment]
I'm on `0.0.4-rudy` because I wanted the `basename` feature mentioned [here](https://github.com/faceyspacey/redux-first-router/issues/103#issuecomment-329972201). It works great and has all of the features that I currently need.

Mostly, RFR stays out of my way and I don't have a ton of code that directly interfaces with it. So, I don't expect that the breaking changes will be too painful to deal with.
