### ISSUE TITLE
alternatives to thunk data requests

### ISSUE THREAD

**Issue by tyrsius** [faceyspacey/redux-first-router#18]
The docs say

>... we recommend strategies that totally avoid thunks, such as Apollo's GraphQL client. Think of the thunk feature as a fallback or for simpler apps.

If you aren't using the GraphQL Client you are left thinking "I am doing something wrong" without any idea of what the alternatives are. I think more detail should be given about what recommended strategies avoid thunks, preferably with an example.

**Comment by faceyspacey** [comment]
Reading that now, I actually wanna downplay graphql and Apollo given how much more useful the things I feature has just become. Now ur thunks can be prefetched along with chunks. 

In general, specifying thunks associated with routes like this really gives Apollo a run for their money. Only if u really have a large project with lots of relational data does Apollo make sense. 

So that said, we definitely don't wanna make people feel like they are doing something wrong. We want people using this solution, especially given how much power it's been given regarding SSR, splitting and prefetching.

**Comment by faceyspacey** [comment]
I may just shut up about Apollo so developers who weren't even thinking about graphql just use this. People already using Apollo will know what to do. Maybe one simple line that it works with Apollo is all that's needed somehwere.

**Comment by faceyspacey** [comment]
changed this FAQ to:

```js
What if I don't want to use the *thunk* feature, can I use other ways of requesting the data?
> Of course. This work along side any middleware of your choosing, and even GraphQL solutions like Apollo. But for the 80% use-case, "follow-up" thunks attached to routes gets a lot of bang for your buck via the context associated with the initial route action.
```
