### ISSUE TITLE
Url on address bar is not decoded!

### ISSUE THREAD

**Issue by DevAnouar** [faceyspacey/redux-first-router#215]
I'm using a dynamic segment which contains special characters in its payload (i.e. '@' and ','). The Url displayed in the address bar is not decoded.

This is using the **Rudy** branch and the action dispatched looks something like this:

`{ type: 'NEARBY_SHOPS', payload: { perimeter: `@${34.0456296},${-6.8101777},${30}` } }`

Which generates a URL like this: `http://localhost:3000/nearby/%4034.0456296%2C-6.8101777%2C30`. Though, I want to display the URL decoded as: 
`http://localhost:3000/nearby/@34.0456296,-6.8101777,30` 

Would you please clarify on how to do this!

**Comment by faceyspacey** [comment]
Unfortunately, in the current version of RFR@rudy, the standard `encodeURIComponent` call is always applied. Paste this in your console:

```js
encodeURIComponent('@34.0456296,-6.8101777,30')
// result: "%4034.0456296%2C-6.8101777%2C30"
```

This is fixed in the next major version, which will be out in a few more weeks. In the next version, all underlying libs are now using options to do ***no*** encoding/decoding when using the `to/fromPath` options, leaving it up to you to do how you wish.

For now, I might try using a query key/val instead:

https://github.com/faceyspacey/redux-first-router/blob/master/docs/query-strings.md

And if you really need it in the path, you may be able to get closer to what you want using the `route.to/fromPath` options.
