### ISSUE TITLE
Include AJAX-fetched data in page title?

### ISSUE THREAD

**Issue by lydell** [faceyspacey/redux-first-router#217]
- `/`: Products listing. Clicking on a product takes you to for instance `/product/12`.
- `/product/:id`: Product detail page.

On the start page I want the page title (`document.title`) to be: "MyStore". Easy enough.

On the product page the page title should be for instance: "Rolex watch – Mystore". When this page is entered, I fetch the product details with AJAX (from `/api/v1/products/12` for instance). When the request is done I have access to the product name ("Rolex watch") and want to put that in the page title. However, redux-first-router seems to only update the page title when the current location changes, not when arbitrary state updates.

Am I missing something?

Just tell me if you need more details :)

**Comment by lydell** [comment]
I ended up passing `title: () => undefined,` to `connectRoutes` as a way of disabling title support in redux-first-router and using [react-helmet](https://github.com/nfl/react-helmet) instead.

**Comment by faceyspacey** [comment]
that's a fine solution. you can also set `document.title` manually any time you want on the client, if you want to avoid a large dependency just for a one liner. ...for SSR, it's just a matter of grabbing `state.title` and putting it in the HTML you spit out. since this isn't dependent on RFR updating the browser's `document.title` when used on the server, `state.title` will work fine. Essentially you're using Helmet now just for the client side aspect.

Here's another way you might like:

```js
store.subscribe(() => {
   if (getState().title !== getState().title) document.title = getState().title
})

// and:

title: isClient() ? () => undefined : 'title'
```

that way it still works as expected on the server, and on the client you update the title on every single title change automatically. no extra libs needed. very few extra lines of code.

**Comment by faceyspacey** [comment]
ps. dont be afraid of the `subscribe` call--that's what every single connected component is doing, and more (comparing props equality). you could end up with dozens of connected components each with their own subscriptions. this is super minor in terms of perf.

**Comment by lydell** [comment]
Thanks for the quick and awesome answers!

But ... why does the title functionality in RFR even exist if it ... requires workarounds in all but the simplest cases? :)

**Comment by faceyspacey** [comment]
That’s the most common use case and all many people need

**Comment by hedgepigdaniel** [comment]
If I'm not wrong, in the upcoming Rudy release it will be possible to have change the order of data fetching and title setting, and each step in the pipeline waits for the previous (async) step to complete. So you could either
 * Fetch data from a promise in `beforeEnter` instead of a synchronous function in `thunk`
 * Customize the order of middlewares such that the setting of the title occurred after the `thunk` (which would need to be a promise) or wherever you load the page title data.

**Comment by faceyspacey** [comment]
exactly.

here's the default middleware:

```js
middlewares: = [
    serverRedirect,       // short-circuiting middleware
    anonymousThunk,
    pathlessRoute('thunk'),
    transformAction,      // pipeline starts here
    call('beforeLeave', { prev: true }),
    call('beforeEnter'),
    enter,
    changePageTitle,
    call('onLeave', { prev: true }),
    call('onEnter'),
    call('thunk', { cache: true }),
    call('onComplete')
  ]
)
```

*here's another option to inspire some ideas:*

```js
middlewares: = [
    pathlessRoute('thunk'),
    transformAction,
    call('filter'),
    call('before', { cache: true, dispatchStart: true }),
    enter,
    call('after')
  ]
)
```
