### ISSUE TITLE
How to change a matched route to a NOT_FOUND?

### ISSUE THREAD

**Issue by waynebloss** [faceyspacey/redux-first-router#219]
I'm trying to figure out where in the routing pipeline can I change a matched route to `NOT_FOUND`?

Currently I'm focusing on using the `onBeforeChange` handler (I'm on `0.0.4-rudy`).

First I tried doing `dispatch({type: NOT_FOUND});` but there was an error. Then I decided to just alter the `change.action.type = NOT_FOUND` using the last argument of `onBeforeChange(dispatch, getState, change)` and that seems to work beautifully.

Is this the correct and future-safe way to implement this functionality? Thanks!

**Comment by faceyspacey** [comment]
I'm not exactly sure what the error was. It shouldn't be an error to begin with. Are you using a custom location instead of `state.location`. There was a bug for that fixed if you were using the `@rudy` tag, which is fixed if update to the latest `@rudy` tag.

The future will ultimately mean lots of changes, as the real Rudy is very different. So I'd just stick with what works for now. Using the optional argument if that somehow worked is fine.

**Comment by waynebloss** [comment]
Thanks.

The error I'm getting is:

TypeError: Cannot read property 'pathname' of undefined
./node_modules/redux-first-router/dist/action-creators/middlewareCreateNotFoundAction.js.exports.default:

```js
 var meta = action.meta;
> 20 | var prevPath = location.pathname;
  21 | 
  22 | var kind = meta && meta.location && meta.location.kind || // use case: kind === 'redirect'
  23 | location.kind === 'load' && 'load' || 'push';
```

**Comment by waynebloss** [comment]
I just put that there for anyone else who might have run into it.

**Comment by faceyspacey** [comment]
so you must be using a custom location for your `location` reducer. update to the least @rudy tag. it should be: 0.0.8-rudy. that bug has been fixed.

**Comment by Daniellt1** [comment]
@faceyspacey, is there any way to achieve redirects mentioned in https://github.com/faceyspacey/redux-first-router/blob/master/docs/server-rendering.md#redirects--not_found-example with custom reducer location using `0.0.20-next` version?
