### ISSUE TITLE
routesMap: generic regex takes precedence before more specific route

### ISSUE THREAD

**Issue by pmrukot** [faceyspacey/redux-first-router#273]
I may have missed something, but at least the question is very specific. I have following route map:
```JS
SPECIFIC: {
  path: '/specific'
},
GENERIC: {
  path: '/:generic+',
}
```

The thing is, that I cannot really access `SPECIFIC` route through the browser. The route is being resolved correctly while using `redux-first-router-link` + `to` prop + action, however when I refresh the page (or just enter the URL from outside of the app), I get the screen/content from the `GENERIC` route.

So the question is, is there an option to make more specific routes take precedence before the more generic ones? 

I kinda realise that the routes design here may not be the smartest, and I probably should have some constant prefix before the `GENERIC` route, was just wondering if its somehow possible.

Already looked here: https://github.com/faceyspacey/redux-first-router/issues/83#issuecomment-327703226 but haven't really found any answer.

**Comment by hedgepigdaniel** [comment]
There is another issue somewhere here where this was discussed.

Pretty sure RFR it uses the first route that matches (first as in the first key in `Object.keys(routesMap)` where the path matches the current URL).

In most browsers, the order is the order you insert them into the object, as long as the action strings start with letters. Maybe try doing `Object.keys(routesMap)` and make sure the more specific route is first?

**Comment by ScriptedAlchemy** [comment]
@hedgepigdaniel, i think our coming update should rectify some of these issues, correct? 
@pmrukot have you tried the `@next` tag on NPM? does it still give you the same issue

**Comment by hedgepigdaniel** [comment]
I've had this issue on the `rudy` branch, so I don't know of a fix other than working around it by doing one of:
- Making sure the more specific action types appear in routesMap first. Caveats are:
  - your action types cannot start with numbers otherwise insertion order is not preserved (don't ask...)
  - You can't maintain the order if you add routes dynamically
  - You might end up with confusing behaviour since you can still reach either overlapping route if you dispatch the appropriate action.
- Making sure that the routes do not overlap (for example if you have updated to `@next` or `@rudy`, you can probably use [regexes](https://github.com/faceyspacey/redux-first-router/issues/83#issuecomment-327703226) to exclude `"specific"` as a value for the `generic` parameter.

Making the routes not overlap is IMO probably a better solution - some short term pain to construct the right regex but no [mysterious behaviour](https://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order) arising from the order of keys in JS objects.

**Comment by hedgepigdaniel** [comment]
Related: https://github.com/faceyspacey/redux-first-router/issues/50

Adding an `order`/`priority` value to routes could also be a neat solution. That would avoid the regex pain and still work with dynamically added routes etc.

I'm curious what happens if you dispatch an action where the payload params don't match the regex? One possible disadvantage of the `order`/`priority` is that you can still get confused by dispatching an action like
```javascript
{
  type: 'GENERIC',
  payload: {
    generic: 'specific',
  },
}
```

Perhaps in that case it should detect that the route is unreachable and throw an error - or redirect to the route that is matched by the resulting URL. Its a strange situation to be in.

Is there a good reason why you would need this in an app, (other than having to support some existing URL structure)? It would be simpler if instead of having `/posts/:postId` and `/posts/new` you had `/posts/new` and `posts/post/:postId`. I.e., don't assign multiple meanings to the same value.

**Comment by ScriptedAlchemy** [comment]
Daniel this will be a good one to test in our demo. I believe it was patched in Rudy Respond

**Comment by dentrado** [comment]
+1 for adding an order/priority value. Sometimes you don't have a choice to make non overlapping paths, if you need to support an existing URL structure eg. as @hedgepigdaniel said.

**Comment by Grsmto** [comment]
Reach Router has a "ranking" system: https://reach.tech/router/ranking
Which means it doesn't resolve path based on order, which I think is probably the smartest way to do this. Especially with dynamically loaded route that makes the thing very complex to maintain at the moment.

**Comment by ScriptedAlchemy** [comment]
Hmm, this is a good point. I do like the idea of ranking.

**Comment by ScriptedAlchemy** [comment]
Will open this issue again on a new repo. RFR will be entering LTS and Rudy will be where new features are added. Ill update the readmes once i move it off a branch on this repo
