### ISSUE TITLE
iOS Chrome "#" to "%23" Routes

### ISSUE THREAD

**Issue by luapaaron** [faceyspacey/redux-first-router#281]
Hi,

I've got a problem regarding the routes in adding hash.

In windows chrome browser when I add hash using this:
window.location.href += '#openModal'
the url is becomes like this: www.domainName.com/pathName#openModal
if I refresh the page, the routes still goes to the "pathName"

but in iOS chrome. when i add window.location.href += '#openModal'
the url becomes like this: www.domainName.com/pathName%23openModal
then I refresh the page, the routes leads to NOT_FOUND

any suggestion how can I handle this?

Thank you

**Comment by ScriptedAlchemy** [comment]
can you try with the `@next` tag on npm?

**Comment by hedgepigdaniel** [comment]
This doesn't look like a problem with redux-first-router - it is correct to parse `/pathName%23openModal` to `NOT_FOUND` unless you have a route for it.

It looks like the problem is that `window.location.href += hash` is not a reliable way to set the hash.

If you want to try it, the (currently unstable) rewrite in https://github.com/ScriptedAlchemy/redux-first-router/tree/rudy-respond has full support for hashes in URLs - they are handled inside the reducer, similar to how path and query params are before the rewrite.

**Comment by luapaaron** [comment]
you mean upgrade my redux-first-router?

I did but still when i refresh the page when it is www.domainName.com/pathName%23openModal, it still not found..

my current version is "redux-first-router": "0.0.20-next"

**Comment by ScriptedAlchemy** [comment]
Its not been released yet, youd have to pull the repo down or install via git :) we are working on getting a stable beta out for people

**Comment by luapaaron** [comment]
ok will try thanks
