### ISSUE TITLE
Example with Create-React-Native-App

### ISSUE THREAD

**Issue by msell** [faceyspacey/redux-first-router#35]
Sorry if this is not the right place for this discussion, but I'm having problems configuring redux-first-router with a CRNA (Create-react-native-app).  Does anybody have a good example?

**Comment by eudaimos** [comment]
@msell I'm in the process of building an app that started from CRA (not familiar with CRNA), but I can say it has to be `eject`ed to get access to the webpack config and then it's a nightmare after that - I wish I would have started from scratch

Now I'm implementing SSR with my own server so that definitely added some complexity, but I feel like CRA is for marketing prototyping and not for starting to build from

**Comment by faceyspacey** [comment]
Have you checked the latest demo. It's focused on SSR:

https://github.com/faceyspacey/redux-first-router-demo

I have yet to release an article describing it, but it's been polished for a week.

**Comment by faceyspacey** [comment]
...there's a demo by the way using this with RN and React Navigation:

https://github.com/faceyspacey/redux-first-router-navigation

Also make sure to check the RN docs:

https://github.com/faceyspacey/redux-first-router/blob/master/docs/react-native.md

i assume it shouldn't be very different with CRNA. I'd be interested to know if there are any differences. @msell let us know if u have any luck. Im gonna close this for now.
