### ISSUE TITLE
Non-React Compatibility

### ISSUE THREAD

**Issue by alexstanbury** [faceyspacey/redux-first-router#38]
Would it be  possible/feasible to integrate this router with frameworks/libraries other than React?

**Comment by iansinnott** [comment]
Totally! The core dependency of redux-first-router is Redux, which [is unrelated to React](http://redux.js.org/docs/basics/UsageWithReact.html#usage-with-react):

> From the very beginning, we need to stress that Redux has no relation to React. You can write Redux apps with React, Angular, Ember, jQuery, or vanilla JavaScript.

Just dispatch actions to navigate. The `Link` component does depend on React but you don't need it to use redux-first-router, which is why it's in a separate package.

**Comment by faceyspacey** [comment]
@alexstanbury also the Link package is super small. It's a bit more complex than it needs to be--but if you wanted to remake it for another framework, it would be extremely simple. I can also help you with this if you need to make it.

Basically it's a case of calling `store.dispatch` in your Link component. You need your `routesMap`. If you need to get this done quickly, you can just import it yourself since you make the `routesMap` and userland. The general-purpose way to build this is to get your `routesMap` off of `store.getState().location` as per:

https://github.com/faceyspacey/redux-first-router-link/blob/master/src/Link.js#L50

In React the redux store as context is used to idiomatically get access to the store. So you'll want to use the equivalent in the framework you're using.

What framework(s) do you have in mind by the way?

**Comment by alexstanbury** [comment]
Thanks for the replies. I was thinking primarily about angular (2+), but then it seems using ngrx/store is the way to go with that.
