### ISSUE TITLE
RFR Dispatches previous route action

### ISSUE THREAD

**Issue by KaRkY** [faceyspacey/redux-first-router#52]
Hello,

I have found wierd behaviour with RFR. When I dispatch route action with meta.location.current.query = undefined current route action is dispatched and next action for route that I am trying to enter is dispatched.

Example where this behaviour is displayed https://codesandbox.io/s/gJjzq3O86. Watch in console what happens when you click on todo button.

**Comment by faceyspacey** [comment]
so you're referring to the extra dispatch of `HOME` at the beginning?

You're not supposed to manually provide the `location` object in the action right? Is this just to demonstrate what happens when query has a key but that is `undefined`? The code won't add `query` to `location.current` if it's undefined.

???

**Comment by KaRkY** [comment]
Yeah I was referring to extra HOME action.

Ok did not know I schould not set that key. Then this is not a problem.

**Comment by faceyspacey** [comment]
Cool. just re-check the docs to see the 3 places you can put it. If the problem occurs there too, reopen this.
