### ISSUE TITLE
Splitting reducers?

### ISSUE THREAD

**Issue by husek** [faceyspacey/redux-first-router#57]
Hi there,

I've used RR3 in the past, and it was quite easy to split reducers depending on the route, it's possible to achieve the same using redux-first router?

That's was my previous approach:
https://stackoverflow.com/a/33044701

Cheers.

**Comment by faceyspacey** [comment]
@husek thanks for joining RFR. A feature named something like `addReducers(newReducers)` will be out in about a week. I'm ust gonna close this since it's comin no matter what. It will be easier before. You will be able to use the `onLoad` callback of our ***React Universal Component*** package to simply call `addReducers`:

https://github.com/faceyspacey/react-universal-component#api--options

```js
import universal from 'react-universal-component'
import { addReducers } from 'redux-first-router

const UniversalComponent = universal(props => import(`./props.page`), {
   onLoad: module => addReducers(module.reducers)
}

it will expect a hash of reducers.

**Comment by faceyspacey** [comment]
tho actually it may still have to be replaceReducers, and require the user to rebuild the whole thing, since combineReducers returns a reducer without any knowledge of the keys. damn. ok, well, we'll have the feature.

**Comment by husek** [comment]
@faceyspacey interesting, I've tried something like that and it kinda worked.

I've tried something like this:
```  
const components = {
  Home: universal(({ store }) => {
    const AppDuck = require('redux/modules/app').default;
    injectAsyncReducer(store, 'app', AppDuck);
    return import('containers/Home');
  }, {
    minDelay: 500, // match sliding animation duration
    loading
  })
};
```

Although it does work, my thunks no longers worked.
You see, it was like the thunks are solved before the universal component, so by the time the thunks dispatch actions, the reducers weren't merged yet, do you think your approach might be able to solve that?

Btw, if you want to, I can collaborate with my injectAsyncReducer code, that will probably do the trick regards the combineReducers thing.

**Comment by Daniellt1** [comment]
@husek, have you managed to find a solution?

**Comment by husek** [comment]
@Daniellt1 if you consider no longer splitting reducers a solution, yes I did find one :rofl:

**Comment by ScriptedAlchemy** [comment]
Well, someone actually opened an issue on how to do this. 

You should be able to do it in onLoad. Check out all the options under RUC. 

Also RUC has been merged and refactored into React as React.Suspense. 

The api is pretty similar (no surprise) so it’s super easy to just move over. 

We will be writing a migration document. However we don’t know how effective the chunk flushing is. So Universal May live on but using suspense under the hood. 

Reducer splitting is possible. Just harder.

REdux-first-router and Rudy are far more robust.

Rudy will have nested routing and the ability to reload and prefetch routes. It also run before react so you know where the user is going ahead of time.

**Comment by raRaRa** [comment]
I've been keeping my eyes on https://github.com/Microsoft/redux-dynamic-modules

It allows you to create modules that have reducers and middlewares, which can be injected during run-time or using HOC.

**Comment by hedgepigdaniel** [comment]
I like the idea of that stack overflow answer. I like to do something similar with redux-first-router:

```javascript

// thunks/settings.js
import { injectReducer } from '../reduxThings';
import { settingsReducer } from '../reducers/settings';

export const loadSettings = (dispatch, getState, bag) => {
  const { extra: { injectReducer } } = bag;
  injectReducer('settings', settingsReducer);
  // Do other stuff, load data, etc
};
```

```javascript
// setupController.js
const routes = {
  'HOME': '/',
  'SETTINGS': {
    path: '/settings',
    thunk: (dispatch, getState, bag) => import('./thunks/settings')
      .then(({ loadSettings }) => loadSettings(dispatch, getState, bag)),
};

connectRoutes(routes, {
  extra: {
    injectReducer,
  },
});

```

**Comment by Daniellt1** [comment]
@ScriptedAlchemy, this old discussion from Gitter describes my issue very well:

> Jeff Hoffer Aug 08 2017 22:51
when you talk about using the onLoad event to replace or add reducers, etc. how is this affected on the server?
Specifically, if I’m adding reducers for a component in onLoad then those reducers won’t be in the store when I fire off actions that will populate the store for rendering on the server since the onLoad event won’t be called until I call ReactDOM.renderToString(…) or am I misunderstanding the lifecycle?

> James Gillmore Aug 09 2017 05:28
that’s a tough on. based on the store pre-population strategy no.
but if component lifecycle methods were to dispatch actions (after onLoad), yes.
i just had an idea:
on the server, always have all your reducers added
then when it comes to preparing window.REDUX_HYDRATION_STATE, remove the keys that weren’t used.
onLoad would simply buffer you an array of the reducers used
and then then just subtract those reducers used from all potential dynamically added reducers
then remove those keys from the hydration state json
...that’s just a quick off the top solution, but you’re right this stuff isn’t complete thought through in terms of Redux.

I need to inject reducers first and then populate the state from a route thunk. I can't do injection in route thunk because it happens only on server (for example for initial load). I can't do that in onLoad either because route thunk happens earlier. I potencially could do that in both places, however, that sounds too dirty. I am just wondering is there any better solution than the proposed by James?

**Comment by hedgepigdaniel** [comment]
> I can't do injection in route thunk because it happens only on server (for example for initial load)

Right yes, I haven't tried it with SSR but it makes sense that that wouldn't work. I never checked - does `onBeforeChange` run on the client side after SSR?

If you record the reducers you need in your routes, then I'm sure there's a way to inject them when the app renders on the server and hydrates on the client. Perhaps you could check the action type of the first route before dispatching it in `configureStore`, look up the reducers from your routesMap, and inject them before dispatching the initial route action?

I think you could do similar to what I suggested (and still have it work with SSR) pretty simply with Rudy. Since Rudy allows multiple callback middlewares (not just `thunk` but also `onBeforeChange`, `onEnter`, or any others you define). You could probably define one that runs on both the server and the client, and that runs before `thunk` or whatever you use to load your data.

```javascript

createRouter(routes, options, [
  serverRedirect, // short-circuiting middleware
  anonymousThunk,
  call('addReducers'),  // This one could find `route.reducers` and inject them (asynchonously) before the thunk etc
  pathlessRoute('thunk'),
  transformAction, // pipeline starts here
  call('beforeLeave', { prev: true }),
  call('beforeEnter'),
  enter,
  changePageTitle(),   call('onLeave', { prev: true }),
  call('onEnter'),
  call('thunk', { cache: true }),
  call('onComplete'),
])
```

You could also write your own middleware to do that if that makes it neater.

My feeling about this is that adding reducers from components is an anti-pattern - because its exactly the kind of cross cutting controller concern that RFR/Rudy aims to take away from components. `App = F(state)` and the view being a pure function is not really compatible with the view adding reducers to the redux store.

**Comment by ScriptedAlchemy** [comment]
Agreed, though understand what the scenario is. With some challenge I have been able to split reducers into backend only and shared. If we don’t already cater for a solution in Rudy, it’s something we should definitely look into. Like a beforeRender oh something
