### ISSUE TITLE
little api improvement: let enhancer wire up reducer and middleware

### ISSUE THREAD

**Issue by c0d0g3n** [faceyspacey/redux-first-router#84]
@faceyspacey Hi, I'm not actually using your package but I'm implementing something similar myself (you did a great job regardless). When browsing through your docs and code, I think I found some kind of oddity: **RFR is using a store enhancer, but you require the user to hook up the reducer and middleware themselves.** You could refactor the enhancer in a way that it automatically wires the reducer and middleware to the store. ([L406](https://github.com/faceyspacey/redux-first-router/blob/master/src/connectRoutes.js#L406)) That would make setting up even more convenient. (Or is this a deliberate design descision?)

I know, it's nitpicking, but I thought you'd want to know. :)

**Comment by c0d0g3n** [comment]
After some more tinkering, I think the choice was deliberate and the right one; putting everything in the enhancer makes developing one a lot more complicated as other packages basically had the same idea. That means you cannot rely on state and action shape anymore (redux devtools wraps both f.i.). The order of enhancers becomes very important, which means you can potentially not use `composeWithDevtools` anymore.

Maybe there's still improvement for the redux extension system. Anyway, I'll close this one.

**Comment by faceyspacey** [comment]
Truth is it wasn't deliberate, and it never occurred to me until now. I really like your idea. If it was foolproof I would do it, but order does matter for middleware, and letting users be in control of the order is important. 

As for tacking on the reducer, I guess that's just a matter of making a new function and combining the results of the passed reducer with the `location` reducer into the returned state object. It's a minor performance overhead creating that extra object--I'm not sure we want to do that.

**Comment by faceyspacey** [comment]
@c0d0g3n I'm actually thinking of going this route. What did you mean by this:

> That means you cannot rely on state and action shape anymore

??
Basically state seems reliable:

```js
const rootReducer = (state, action) => {
      const nextState = reducer(state, action) || {}
      nextLocationState = locationReducer(state && selectLocationState(state), action)
      setNextLocationState(nextState, nextLocationState)
      return nextState
}
```

So `selectLocationState` is a function we already have, and it defaults to `state.location`. We don't have `setNextLocationState`, but it can be added. 

Ultimately, what I'm working on is a lot more than just simplifying the return down to just the `enhancer`. I have a new setup that "captures" actions before they even hit the standard redux middleware, and then runs the action through a *koa-like* middleware pipeline. I.e. a promise-based one. This allows for many things, the primary example being: you can redirect or decide not to change routes in promises without having to do hacky double-dispatch implementations in the primary redux middleware. Before, if you used `confirmLeave` (which will soon be called simply `beforeLeave`) to `return false` and prevent route changes, in the case that you used promises, but you didn't return `false`, we'd have to always block the first action, and then re-dispatch the same action, and have it go back through the middleware, skipping over parts it executed the first time. The implementation is horrible, given redux middleware is synchronous--i.e. since it can't honor promises. As for redirects, they too result in double dispatches.

Anyway, I have a new super slick setup where you can now think of your redux middleware as unwrapping promises before passing the action to the next middleware, which also gives you *"rewind"* capability to operate on the action yet again after next middlewares handle it and before the previous ones.

So that's the route I'm going here, and to do it the cleanest implementation involved writing this all as its own enhancer, rather than middleware. Only when it's done doing it work, and if it chooses to, will actions be dispatched through the standard middleware. So my point is we no longer have the middleware ordering problem. And as far as the enhancer order, the precise prescription is it must go after the dev tools enhancer, and more importantly BEFORE everything else, particularly your regular middleware. If it doesn't go before your regular `applyMiddleware` enhancer, it simply won't be able to work.  Other things can go before if you have a good reason, but in terms of what comes after, `applyMiddleware` must always go after. Given how many new capabilities the new setup opens up, it's a more than worthy tradeoff. 

Also, what did you mean by:
> putting everything in the enhancer makes developing one a lot more complicated **as other packages basically had the same idea**

?

I just want to make sure I'm getting this right. Perhaps the only real tradeoff is that developers can't pre-transform the action before it hits RFR via other middleware. There's a lot of existing middlewares out there--are they any popular ones where that would matter? Ultimately something as important as a router has a bit more claim to position in the middleware than other things. The middlewares or enhancers that go first have the most control. So the thinking is that most of the time it belongs first.

**Comment by c0d0g3n** [comment]
@faceyspacey I meant that the shape (tree structure of object, property names...) of both action and state will vary depending on what other enhancers you use in your app.

E.g. the state that redux devtools produces is an array of state snapshots and a pointer to indicate which state is currently active.

```js
const state = {
  0: [state at t=0],
  1: [state at t=3],
  2: [state at t=5],
  ...
  pointer: 2, // state at t=5 is currently active state (don't remember exact property)
}
```
If you use `state.reduxFirstRouter`, you will get `undefined` because, clearly, that property is not defined. You will however find `reduxFirstRouter` as a child of both `state[0]`, `state[1]` and `state[2]`.
This is only one example of how a third party enhancer can modify the state (and actions) and render your assumptions about those objects unusable.

Your second request for clarification boils down to above.

If you want my opinion: I would never modify the contents of action or state, except in your own namespace (if I understand correctly, you are not planning to). However, some projects did (e.g. redux devtools), therefore you should require redux-first-router to be loaded first, otherwise it won't work for above reasons.

Regarding async: I would stick with the community model of dispatching start, success and cancel actions. Also consider whether those actions may be useful to build other middleware on. (I.o.w. probably don't swallow them.) It will pollute the action "stream" a bit more, but that can be solved with better tooling (e.g. more, flexilble and permanent filters in redux-devtools). It's IMO the most "correct" way.

Then again, I hardly have experience with the ecosystem, but this is what I thought about and you might want too.

Hope this helps. I'm sorry if I only partially answered your message. (Also I'm recalling this from the top of my head so some pieces of data may be slightly inaccurate.)
