### ISSUE TITLE
onAfterChange doesn't wait for an asynchronous onBeforeChange to finish

### ISSUE THREAD

**Issue by TomsOzols** [faceyspacey/redux-first-router#85]
Basically - I've got a check and fetch if missing situation, for some initial application info (like current user details), that I'd like to perform for any and all routes.

The way I was trying to achieve it up till now - to make a server call inside of the onBeforeChange function, but this attempt failed since onAfterChange doesn't wait for onBeforeChange to finish, and onAfterChange relies on what is being fetched previously.

Not sure if I'm barking up the wrong tree here - but is this intentional?

Recently switched over to this wonderful router - and have finally come to the first refactor effort after running with it for a while. Still considering where to place all the involved parts of My application in relation to the router, and this just came up, and if at all possible, wanted to hear Your opinion on this.

**Comment by faceyspacey** [comment]
Unfortunately `onBeforeChange` is synchronous, as Redux's middleware is synchronous and it runs within it. Your query does make me wonder if I could rework things to operate asynchronously here. I  probably could, but it would be a significant change. Something related I've been thinking about is remaking Redux itself so it processes middleware asynchronously. It can be done. That would solve your issue as well as the improve the server-side rendering strategy where a `thunk` is returned that you manually wait on. Basically if Redux middleware could be processed truly asynchronously, the entire middleware chain could be awaited on. 

Now that all said, ideally you aren't making a server call in every `onBeforeChange`. That's a lot of unnecessary time your users have to wait between routes now. You ideally get the user information once on load (or passed from the server if doing SSR), and then you can synchronously check if the user is authenticated based on a JSON Web Token you already have (or user object retrieved once using a `sessionId` cookie). 

Another way to achieve it is to use `onAfterChange` to dispatch the  request for user auth details, and hide the views you need to be authenticated to view until the response returns and changes some state. 

I still think you likely just want to avoid authenticating on every page change like that. I assume you're doing it once via a promise, and then in the future just checking state, but returning a promise that resolves 1 tick later for consistency. In that case, again the best strategy is to do the async auth only once on setup.

That all said, I surely hope the issue you're having isn't a common strategy/idiom, or it will take some serious reworking of the router. The implementation for this sorta thing certainly won't be clean since Redux middleware doesn't support it out of the box. It basically means pausing a route change action, monkey-patching the `dispatch` function passed to `onBeforeChange`, and only once you call it with the data does it dispatch both your action which sets the data and the original action that changes the route. It might even be best served with a custom action creator like this: `dispatch(completeRouteChange())`. Because you could do multiple dispatches, and we would need to know which is the final one that should trigger the route change.

**Comment by TomsOzols** [comment]
Thanks for the detailed response!

You've thrown some nice ideas My way, and they've definitely opened up My eyes for this, and maybe even some other issues I've been facing.

Probably going to close this issue now, since I've heard what I came for. Would be fun to find a use-case where this would be a must have though :).

Well, anyways, best wishes and happy coding!
