### ISSUE TITLE
Most idiomatic way to group routes

### ISSUE THREAD

**Issue by villesau** [faceyspacey/redux-first-router#92]
Hi,

I came across the redux first router and it looks really good. Maybe the first really redux-first designed router i've seen!

You have made decision to not to have nested routes. And when looking at the shape of the route object, it indeed makes sense: It does not make sense to i.e dispatch multiple different route-type actions in case of nested routes. But it might make sense to call different thunks.

Anyhow it makes certain approaches difficult. Let's say i have wizard where i can land on every page (wizard_start, wizard_middle, wizard_end). Therefore i need to initialize same data for each page. This can be achieved by having same thunk for all of the pages. But it does not solve the problem completely: If i land to wizard_start, and move to wizard_middle, the thunk is dispatched again. That's something i don't want: I want my wizard pages to be grouped so that the thunk is dispatched only once, no matter which page i land first.

is there some idiomatic way in redux-first-router to achieve this currently? What i'm actually asking for is functionality for grouping routes together. Something like this:

``` javascript

const routes = [
  {
    routes: { //grouped wizard routes
      START: {url: '/wizard/start'},
      MIDDLE: {url: '/wizard/middle'},
      MIDDLE_BRANCH: {
        url: '/wizard/middle/:param',
        thunk: (dispatch, getState) => {
          // some routes within group could have custom logic for initializing
          // in addition to common thunk
          dispatch(loadBranchSpecificData(getState().route.param))
        }
      },
      END: {url: '/wizard/end'}
    },
    thunk: (dispatch, getState) => {
      // this would be called only once when you land on any route within group
      dispatch(initializeWizard())
    }
  },
  {
    type: 'SOME_OTHER_ROUTE',
    thunk: (dispatch, getState) => {
    }
  }
]
```

**Comment by faceyspacey** [comment]
Is it not enough to define a route function once and assign it multiple times? And then for the route with a custom function, call the shared one within it?

What's the matter with this approach? Are we just trying to conserve lines/characters?

**Comment by villesau** [comment]
could you elaborate a bit? You mean something like this or something else:

```javascript
const initwizard = (dispatch, getState) => {
  dispatch(initializeWizard())
}

const routes = {
  START: {url: '/wizard/start', thunk: initwizard},
  MIDDLE: {url: '/wizard/middle', thunk: initwizard},
  MIDDLE_BRANCH: {
    url: '/wizard/middle/:param',
    thunk: (dispatch, getState) => {
      initwizard(dispatch, getState);
      dispatch(loadBranchSpecificData(getState().route.param))
    }
  },
  END: {url: '/wizard/start', thunk: initwizard}
}

```

The problem is that i need to be aware if i'm coming from another wizard route to prevent duplicate initialization, and handle that in the initWizard -function somehow. It might easily get messy and error prone to maintain the information about the group.

**Comment by faceyspacey** [comment]
Just examine the action type in the thunk.

It's supposed to be flexible real JavaScript coding that don't require hacks/workarounds. That generally means less "automagic."

Anyway u have full control here based on all the information in the action. Log it and see how much you have.

**Comment by faceyspacey** [comment]
Hey there, we just released optional params and other related advanced ways to define your paths:

https://github.com/faceyspacey/redux-first-router/issues/83#issuecomment-327703226

That will allow you to use the same type for many different kinds of paths. Keep in mind the same type will be dispatched each time it changes. So that doesn't solve the idea of having the thunk only dispatched once. To solve that in your case, you can look at `getState().location.prev.type` to see if the user was already in the wizard, and if not call `initWizard`. 

But the new optional params may make it easier to use one route/type for the entire wizard, and just use parameters in the payload to determine different things to do. This way you don't have to assign the same thunk multiple times. 

That said, I personally would rely on multiple types and re-assigning the thunk so that it's easier to switch over types in reducers. The thunk no matter what is going to have to be smart enough to know when it needs to init itself. And again, `getState().location` has plenty of information for you to make that decision.
